apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-react-app"
  annotations:
    github.com/project-slig: devopsfarm-projects/vercel-deploy
spec:
  type: service
  owner: user:guest
  lifecycle: experimental