apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "{{cookiecutter.project_name}}"
  annotations:
    github.com/project-slig: {{ cookiecutter.destination.owner + '/' + cookiecutter.destination.repo }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental